moppahDjango/accounts/urls.py
# URLS DO MEU APP ACCOUNTS
from django.urls import (path, include, re_path)
from moppahDjango.core.views import (home, contact)
#from moppahDjango.core.views import contact
#from moppahDjango.accounts.views import 
#from moppahDjango.accounts.views import 
from moppahDjango.accounts.views import (edit, edit_password, password_reset, password_reset_confirm,dashboard,register)
from django.contrib.auth.views import (LoginView, LogoutView)
#from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('entrar/', LoginView.as_view(),
        {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', LogoutView.as_view(),
        {'next_page': 'home'}, name='logout'),
    path('cadastre-se/', register, name='register'),
    path('nova_senha/', password_reset, name='password_reset'),
    re_path(r'^confirma_nova_senha/(?P<key>\w+)/$', password_reset_confirm, name='password_reset_confirm'),
    path('editar/', edit, name='edit'),
    path('editar-senha/', edit_password, name='edit_password'),
]

moppahDjango/core/urls.py
# URLS DO MEU PROJETO EM CORE
from django.urls import path
from moppahDjango.core.views import (home, contact)

#app_name = 'core'

urlpatterns = [
    path('',home, name='home'),
    path('contato/',contact, name='contact'),
]

moppahDjango/courses/urls.py
# URLS DO MEU PROJETO EM COURSE
from django.urls import path, re_path
from moppahDjango.courses.views import (courses, details, enrollment, announcements, undo_enrollment,show_announcement, lessons, lesson, material)

app_name = 'courses'

urlpatterns = [
    path('',courses, name='index'),
    #re_path(r'(?P<pk>\d+)/$',details, name='details'), #Adicionar o import re_re_path
    re_path(r'^(?P<slug>[\w_-]+)/$',details, name='details'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/$',announcements, name='announcements'),
    re_path(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$',show_announcement, name='show_announcement'),
    re_path(r'^(?P<slug>[\w_-]+)/inscricao/$',enrollment, name='enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/cancelar-inscricao/$',undo_enrollment, name='undo_enrollment'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/$',lessons, name='lessons'),
    re_path(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$',lesson, name='lesson'),
    re_path(r'^(?P<slug>[\w_-]+)/materias/(?P<pk>\d+)/$',material, name='material')
]


moppahDjango/forum/urls.py
from django.urls import path, re_path
from moppahDjango.forum.views import (index, thread, reply_correct, reply_incorrect)

app_name = 'forum'

urlpatterns = [
    path('',index, name='index'),
    re_path(r'^tag/(?P<tag>[\w_-]+)/$',index, name='index_tagged'),
    re_path(r'^respostas/(?P<pk>\d+)/correta/$',reply_correct, name='reply_correct'),
    re_path(r'^respostas/(?P<pk>\d+)/incorreta/$',reply_incorrect, name='reply_incorrect'),
    re_path(r'^(?P<slug>[\w_-]+)/$',thread, name='thread'),
]

moppahDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('', include('moppahDjango.core.urls')),
    path('conta/', include('moppahDjango.accounts.urls', namespace='accounts')),
    path('cursos/', include('moppahDjango.courses.urls')),
    path('forum/', include('moppahDjango.forum.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moppahDjango/core/models.py
from django.db import models

# Create your models here.

moppahDjango/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

moppahDjango/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <title>MOPPAHTECH PLATAFORM</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    
    
</head>
<body>
<div class="header">
    <div class="home-menu pure-menu pure-menu-open pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="{% url 'home' %}">MOPPAHTECH PLATAFORM</a>
        <ul>
            <li class="pure-menu-selected"><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum</a></li>
            <li><a href="{% url 'contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="content">
    {% if messages %}
    <div class="pure-g-r content-ribbon">
        <aside class="pure-u-1">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
        </aside>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
    <div class="footer">
        MoppahTech Plataform - Sua melhor opção em ensino gratuito a distância 
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% block scripts %}{% endblock %}
</body>
</html>

moppahDjango/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Fale conosco</h1>
        <p>Você pode entrar em contato conosco tanto por e-mail como pelas redes sociais, abaixo seguem os links para contato:</p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a></li>
            <li>Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a></li>
        </ul>
    </div>
</div>
{% endblock %}

moppahDjango/core/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Sua Plataforma de Ensino gratuito a Distância
                </h1>
                <h2 class="splash-subhead">
                    <strong>MoppahTech Plataform</strong> visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos gratuitos a distância.
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Quer saber mais...</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
            <h3>Publique suas aulas</h3>
            <p>
                <strong>MoppahTech Plataform</strong> tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Vídeo aulas e materiais digitais.">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Fórum de Dúvidas">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Fórum de Dúvidas</h4>
            <h3>Interaja com seus Alunos</h3>
            <p>
                No <strong>MoppahTech Plataform</strong> você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
            </p>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Exercícios</h4>
            <h3>Crie exercícios para avaliar seus alunos</h3>
            <p>
                Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
            </p>
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Exercícios">
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <img src="http://placehold.it/400x250"
                 alt="Mural de Avisos">
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Mural de Avisos</h4>
            <h3>Envie anúncios diretamente para os alunos</h3>
            <p>
                Organize os avisos do seu curso de forma fácil e simples.
            </p>
        </div>
    </div>
</div>
{% endblock %}